shell.run("delete startup.lua")
shell.run("delete reedFarm.lua")
shell.run("delete sMove.lua")
shell.run("wget https://raw.githubusercontent.com/SloppyWafer/SloppysCC/refs/heads/main/Turtle%20Programs/startup.lua?token=GHSAT0AAAAAACXEUU2CW3BGQM26T6JATOTOZXRZGRA startup.lua")
shell.run("wget https://raw.githubusercontent.com/SloppyWafer/SloppysCC/refs/heads/main/Turtle%20Programs/reedFarm.lua?token=GHSAT0AAAAAACXEUU2CV4S5BSUMHWZ7JASQZXRZEAA reedFarm.lua")
shell.run("wget https://raw.githubusercontent.com/SloppyWafer/SloppysCC/refs/heads/main/API's/sMove.lua?token=GHSAT0AAAAAACXEUU2CHQKHCMYO4LCIVGZEZXRZHFQ sMove.lua")
